# Hacktiv8 Python for Data Science - Sesi 4

Sesi 3:

- Numpy

## Creating Array

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.arange(4)

array([0, 1, 2, 3])

In [8]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

## Add, Remove, and Sort

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
arrNew = np.append(arr, [1, 2])

In [12]:
arrNew

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [13]:
arrNew = np.delete(arrNew, 1)

In [14]:
arrNew

array([1, 3, 4, 5, 6, 7, 8, 1, 2])

In [15]:
np.sort(arrNew)

array([1, 1, 2, 3, 4, 5, 6, 7, 8])

## Shape and Size

In [16]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

In [17]:
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [18]:
array_example.ndim

3

In [19]:
array_example.size

24

In [20]:
array_example.shape

(3, 2, 4)

## Reshape

In [21]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [22]:
a.shape

(6,)

In [23]:
b = a.reshape(3, 2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [24]:
b.shape

(3, 2)

## Convert 1D to 2D

In [25]:
a = np.array([1, 2, 3, 4, 5, 6])

In [26]:
a.shape

(6,)

In [27]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [28]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [29]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [30]:
a.shape

(6,)

In [31]:
b = np.expand_dims(a, axis=1)

In [32]:
b.shape

(6, 1)

In [33]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [34]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [35]:
c

array([[1, 2, 3, 4, 5, 6]])

## Indexing and Slicing

In [36]:
data = np.array([1, 2, 3])

In [37]:
print(data)

[1 2 3]


In [39]:
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

1
2
[1 2]
[2 3]
[2 3]


In [40]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [41]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
a[a<5]

array([1, 2, 3, 4])

In [45]:
five_up = (a>=5)

a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [46]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [47]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## Creating Array From Existing Data

In [48]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [49]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arrNew = arr[3:8]
print(arrNew)

[4 5 6 7 8]


In [51]:
a_1 = np.array([[1, 1],
               [2, 2]])
print(a_1)

[[1 1]
 [2 2]]


In [53]:
a_2 = np.array([[3, 3],
               [4, 4]])
print(a_2)

[[3 3]
 [4 4]]


In [55]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [56]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [57]:
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [58]:
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [59]:
np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [61]:
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [63]:
b = arrsplit.view()

print(b)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [64]:
c = arrsplit.copy()

print(c)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


## Basic Array Operations

In [65]:
data = np.array([1, 2, 3, 4])
ones = np.ones(4)

In [67]:
print(data)
print(ones)

[1 2 3 4]
[1. 1. 1. 1.]


In [68]:
print(data+ones)
print(data-ones)
print(data*ones)
print(data/ones)

[2. 3. 4. 5.]
[0. 1. 2. 3.]
[1. 2. 3. 4.]
[1. 2. 3. 4.]


In [70]:
print(data.sum())
print(ones.sum())

10
4.0


In [71]:
b = np.array([[1, 1], [2, 2]])
print(b)

[[1 1]
 [2 2]]


In [72]:
b.sum()

6

In [73]:
b.sum(axis=0)

array([3, 3])

In [74]:
b.sum(axis=1)

array([2, 4])

In [75]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [76]:
A.sum()

4.8595784

In [77]:
A.sum(axis=0)

array([1.12378257, 1.04875507, 1.01034462, 1.67669614])

In [78]:
A.sum(axis=1)

array([1.51832856, 1.55434556, 1.78690428])

In [79]:
A.min()

0.05093587

In [80]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [81]:
A.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

In [82]:
A.max()

0.82485143

In [83]:
A.max(axis=0)

array([0.54627315, 0.82485143, 0.40067661, 0.56917101])

In [84]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

## Matrices

In [85]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [86]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [87]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [88]:
np.random.random((3, 2))

array([[0.92226021, 0.43318819],
       [0.24420675, 0.89084479],
       [0.91800638, 0.29613273]])

In [89]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Matrix Arithmetic

In [90]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [91]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [94]:
print(data + ones)
print(data - ones)
print(data * ones)
print(data / ones)

[[2. 3.]
 [4. 5.]]
[[0. 1.]
 [2. 3.]]
[[1. 2.]
 [3. 4.]]
[[1. 2.]
 [3. 4.]]


In [95]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [96]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


## Dot Product

In [98]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [99]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [100]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [104]:
print(data[0, 1])
print(data[1:3])
print(data[0:2, 0])

2
[[3 4]
 [5 6]]
[1 3]


## Matrix Aggregation

In [105]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [106]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [107]:
print(data.max(axis=1))
print(data.min(axis=1))
print(data.sum(axis=1))

[2 4 6]
[1 3 5]
[ 3  7 11]


## Transposing and Reshaping

In [108]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [109]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [111]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [112]:
data_col.shape

(6, 1)

In [115]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [119]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


## N-Dimensional Array

In [120]:
ndarr = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [125]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [128]:
np.zeros((4, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [131]:
np.random.random((4, 3, 2))

array([[[0.4882246 , 0.10389851],
        [0.58848051, 0.67859204],
        [0.7785528 , 0.42225151]],

       [[0.363801  , 0.24722927],
        [0.79298283, 0.80326886],
        [0.92951015, 0.14534498]],

       [[0.36354433, 0.5067065 ],
        [0.04525132, 0.05782362],
        [0.28128721, 0.69389967]],

       [[0.13827522, 0.14155922],
        [0.22517379, 0.30487521],
        [0.9481453 , 0.04072419]]])

## Flaten N-Dimensional Array

In [132]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [133]:
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [134]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Notes on Numpy Vector

In [135]:
a = np.random.rand(5)
print(a)

[0.23922181 0.80742798 0.24476393 0.23992297 0.82203954]


In [136]:
a.shape # Rank 1 Array

(5,)

In [137]:
a.T

array([0.23922181, 0.80742798, 0.24476393, 0.23992297, 0.82203954])

In [138]:
np.dot(a, a.T)

1.502388420652875

In [139]:
a = np.random.rand(5, 1) # column vector
print(a)

[[0.20979547]
 [0.01286554]
 [0.56477516]
 [0.18631046]
 [0.67895426]]


In [140]:
a.shape

(5, 1)

In [141]:
a.T

array([[0.20979547, 0.01286554, 0.56477516, 0.18631046, 0.67895426]])

In [142]:
np.dot(a, a.T)

array([[4.40141378e-02, 2.69913267e-03, 1.18487268e-01, 3.90870907e-02,
        1.42441526e-01],
       [2.69913267e-03, 1.65522206e-04, 7.26613931e-03, 2.39698535e-03,
        8.73511549e-03],
       [1.18487268e-01, 7.26613931e-03, 3.18970981e-01, 1.05223522e-01,
        3.83456501e-01],
       [3.90870907e-02, 2.39698535e-03, 1.05223522e-01, 3.47115889e-02,
        1.26496283e-01],
       [1.42441526e-01, 8.73511549e-03, 3.83456501e-01, 1.26496283e-01,
        4.60978889e-01]])

In [143]:
a = np.random.rand(1, 5) # row vector
print(a)

[[0.93258393 0.96877229 0.21536587 0.55283545 0.92999658]]
